local_costmap:

  global_frame: odom
  rolling_window: true
  
  static_map: false
  width: 2
  height: 2
  resolution: 0.03

  plugins:
    - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}
